remote_theme: mmistakes/minimal-mistakes

title: "Amy Bray Portfolio"
name: "Amy Bray"
description: "People Ops & HRIS Solutions | AI + Engagement | Global Workforce Programs"

# Site settings
url: "https://bramii101010.github.io"
baseurl: "/amybray-portfolio"

# Build settings
markdown: kramdown

# Minimal Mistakes settings
plugins:
  - jekyll-include-cache

# Navigation links
navigation:
  main:
    - title: "Home"
      url: /
    - title: "Projects"
      url: /projects/
    - title: "Case Studies"
      url: /case-studies/
    - title: "Contact"
      url: /contact/
    - title: "Resume"
      url: /AmyBray_Resume.pdf

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
