remote_theme: mmistakes/minimal-mistakes

title: "Amy Bray Portfolio"
name: "Amy Bray"
description: "People Ops & HRIS Solutions | AI + Engagement | Global Workforce Programs"

# Build settings
markdown: kramdown

# Minimal Mistakes settings
plugins:
  - jekyll-include-cache

# Navigation links
main:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "Case Studies"
    url: /case-studies/
  - title: "Contact"
    url: /contact/
  - title: "Resume"
    url: /AmyBray_Resume.pdf
show_excerpts: true
