remote_theme: mmistakes/minimal-mistakes

title: "Amy Bray Portfolio"
name: "Amy Bray"
description: "People Ops & HRIS Solutions | AI + Engagement | Global Workforce Programs"

# Site settings
url: "https://bramii101010.github.io"
baseurl: "/amybray-portfolio"

# Build settings
markdown: kramdown

# Minimal Mistakes settings
plugins:
  - jekyll-include-cache

# Navigation links
main:
  - title: "Home"
    url: "{{ site.baseurl }}/"
  - title: "Projects"
    url: "{{ site.baseurl }}/projects/"
  - title: "Case Studies"
    url: "{{ site.baseurl }}/case-studies/"
  - title: "Contact"
    url: "{{ site.baseurl }}/contact/"
  - title: "Resume"
    url: "{{ site.baseurl }}/AmyBray_Resume.pdf"

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
